// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	authnjwt "github.com/kalandramo/bald-authn-jwt"
	rediscache "github.com/kalandramo/bald-cache-redis"
	"github.com/kalandramo/bald/examples/go-bald-admin/internal/apiserver/biz/v1/auth"
	"github.com/kalandramo/bald/examples/go-bald-admin/internal/apiserver/biz/v1/secret"
	"github.com/kalandramo/bald/examples/go-bald-admin/internal/bootstrap"
	"os"
)

// Injectors from wire.go:

// InitializeBiz 由 wire 生成实现：显式拼装 cache + 两个 biz，依赖图编译期校验。
func InitializeBiz() (*BizSet, error) {
	mainSigner := provideSigner()
	biz := auth.New(mainSigner)
	mainRedisAddr := provideRedisAddr()
	cache, err := newRedisCache(mainRedisAddr)
	if err != nil {
		return nil, err
	}
	secretBiz := secret.New(cache)
	bizSet := &BizSet{
		Auth:   biz,
		Secret: secretBiz,
		Cache:  cache,
	}
	return bizSet, nil
}

// wire.go:

// BizSet 是 wire 装配出的业务对象集合，供 main 注册路由/服务。
type BizSet struct {
	Auth   *auth.Biz
	Secret *secret.SecretBiz
	Cache  *rediscache.Cache
}

// redisAddr 是 wire 的命名类型别名，区分 string 依赖（避免多重绑定冲突）。
type redisAddr string

// provideRedisAddr 从 env 提供 Redis 地址（空=禁用缓存，直连 store）。
func provideRedisAddr() redisAddr { return redisAddr(os.Getenv("BALD_ADMIN_REDIS_ADDR")) }

// provideSigner 从 bootstrap 提供 RSA 私钥签发器（auth biz 依赖 Signer 接口）。
func provideSigner() authnjwt.Signer { return bootstrap.Signer }

// newRedisCache 适配 redisAddr→rediscache.New（保留错误，Redis 不可达即启动失败）。
func newRedisCache(addr redisAddr) (*rediscache.Cache, error) {
	return rediscache.New(string(addr))
}
