package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"

	appspecv1 "github.com/kalandramo/bald/bconf/gen/go/bald/appspec/v1"
)

// appspecTmpl 是 P12 第二步「方言驱动生成」的 main.go 模板：消费 AppSpec，
// 据此装配 appkit 全原语（Capability/S1、Component/C1、Reconcile/R1-2、
// Mount/A1、bundle/P10）。生成的是可运行的装配骨架——业务路由与 gRPC service
// 注册位留 TODO，但框架装配（server/component/capability/reconcile）按 AppSpec
// 真实接线，生成物 go build 通过且 Run 不会因装配顺序问题失败。
//
// 装配纪律（对照 examples/go-bald-admin M10 形状，P12 审查修正）：
//   - servers 与组件一律经 appkit.Servers/appkit.Components Option 传给 New——
//     Option 只有 New 消费，New 之后再 append 无效；Run 之前也不可调
//     MountComponent（要求运行态，Run 内才置位）。
//   - reconcileAudit 是真实可运行的 R1-2 协调器（log 后端开箱即用，
//     store/stream 工厂留 TODO），不再是空壳。
//
// 设计对齐 go-wind-admin 的 proto 分层：把「应用装配」本身升格为单一 proto 真相源，
// 取代 gen app 第一版的硬编码模板（模板 + 手填配置键 = 双真相源）。
var appspecTmpl = `// Code generated by "bald gen app --spec". DO NOT EDIT.
//
// 本文件由 AppSpec 方言驱动生成（P12 第二步）。AppSpec 是应用装配的单一真相源，
// 任何装配变更应先改 AppSpec 再重新生成，而非手改此文件。
//
// 骨架边界：servers/组件/能力声明/审计协调按 AppSpec 真实接线、开箱可运行；
// 业务路由、gRPC service 注册与 store/stream 审计后端为 TODO 填充点。
// module: {{ .Meta.Module }}
package main

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"
	"sync"

	"github.com/spf13/cobra"
{{- if .Server.Http }}
	"github.com/gin-gonic/gin"
{{- end }}
{{- if .Server.Grpc }}
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
{{- end }}

	"github.com/kalandramo/bald/pkg/appkit"
	"github.com/kalandramo/bald/pkg/audit"
	baldlog "github.com/kalandramo/bald/log"
	baldlogadapter "github.com/kalandramo/bald/log/slog"
{{- if or .Server.Http .Server.Grpc }}
	bconf "github.com/kalandramo/bald/bconf"
	"github.com/kalandramo/bald/pkg/middleware/bundle"
{{- if .Server.Grpc }}
	grpcserver "github.com/kalandramo/bald/transport/grpc"
{{- end }}
{{- if .Server.Http }}
	httpserver "github.com/kalandramo/bald/transport/http"
{{- end }}
{{- end }}
)

// defaultAuditBackends 是 AppSpec 声明的审计后端期望态；运行期以 config 的
// audit.backends 为准（未设置时回退到该默认）。
var defaultAuditBackends = []string{ {{- range .AuditBackends }}
	"{{ . }}",
{{- end }} }

func serveRunE(_ *cobra.Command, _ []string) error {
{{- if or .Server.Http .Server.Grpc .Server.HttpAddr .Server.GrpcAddr }}
	bootstrap := bconf.NewBootstrap()
{{- if .Server.HttpAddr }}
	bootstrap.GetServer().GetHttp().Addr = "{{ .Server.HttpAddr }}" // ServerSpec.http_addr
{{- end }}
{{- if .Server.GrpcAddr }}
	bootstrap.GetServer().GetGrpc().Addr = "{{ .Server.GrpcAddr }}" // ServerSpec.grpc_addr
{{- end }}
{{- end }}

	// 日志后端（slog 门面）：logOpts 可被 --log.* flag 覆盖（含 rotate，见 --log.rotate.*）。
	logOpts := baldlogadapter.NewOptions()
	baldlog.SetLogger(baldlogadapter.NewSlogLogger(logOpts))
{{- if or .Server.Http .Server.Grpc }}

	// bundle：横切关注点链序固化（P10）；HTTP/gRPC 双传输共用同一套链。
	b := bundle.New(
		{{- if .BundleNormalized }}
		bundle.Normalized(), // P9 归一化：审计 object/action 双传输同源
		{{- end }}
		// TODO: 业务依赖注入（bundle.Authn(authn) / bundle.Authz(authz) / bundle.Metrics(rec)），
		// 未注入的层自动省略（零开销）。
	)
{{- end }}
{{- if .Server.Http }}

	// HTTP（gin）：bundle 全局链 + 业务路由 TODO。
	router := gin.New()
	router.Use(b.Gin()...)
	// TODO: 注册业务路由（如 router.POST("/v1/ping", ...)）。
{{- end }}

	// 装配：servers 与组件全部经 Option 传给 New（Run 之前完成装配；
	// Option 只有 New 消费，Run 前也不可调 MountComponent——它要求运行态）。
	capOpts := []appkit.Option{
		appkit.Name("{{ .Meta.Name }}"),
		appkit.Version("v0.1.0"),
		appkit.ConfigFile("configs/{{ .Meta.Name }}.yaml"),
		appkit.WatchConfigFile(true),
		// R1-2 期望态协调：以 audit.backends 为期望态，运行期热切审计后端。
		appkit.Reconcile("audit.backends", reconcileAudit),
	}
{{- if or .Server.Http .Server.Grpc }}
	// 配置 flag 覆盖（四源优先级 flag > env > 文件 > 远程）：--server.http.addr / --server.grpc.addr。
	capOpts = append(capOpts, appkit.Bind("server.http", bootstrap.GetServer().GetHttp()))
	capOpts = append(capOpts, appkit.Bind("server.grpc", bootstrap.GetServer().GetGrpc()))
{{- end }}
	capOpts = append(capOpts, appkit.Bind("", logOpts)) // 日志配置 --log.*（含 rotate）
{{- if .Server.Http }}
	// R1 key 级热更新示例：仅当 server.http.addr 值确实变化才触发（与 OnConfigChange 全量互补）。
	capOpts = append(capOpts, appkit.OnKeyChange("server.http.addr", func(old, new string) {
		baldlog.GetLogger().Info(context.Background(), "server.http.addr changed", "old", old, "new", new)
	}))
{{- end }}
{{- if .Capability }}
{{- range .Capability.Provides }}
	capOpts = append(capOpts, appkit.Provides("{{ . }}")) // S1：本进程提供的能力
{{- end }}
{{- range .Capability.Requires }}
	// S1：{{ .Component }} 声明对下列能力的依赖（缺失则启动 fail-fast）。
	capOpts = append(capOpts, appkit.Requires("{{ .Component }}",
{{- range .Caps }}
		"{{ . }}",
{{- end }}
	))
{{- end }}
{{- end }}
{{- if .Components }}
	// 组件：由 ComponentSpec 驱动，kind 决定工厂（C1 生命周期，停机逆序 Dispose）。
	var comps []appkit.Component
{{- range .Components }}
	if comp, err := buildComponent("{{ .Kind }}", "{{ .Name }}", "{{ .ConfigPrefix }}"); err != nil {
		return err
	} else {
		comps = append(comps, comp)
	}
{{- end }}
	capOpts = append(capOpts, appkit.Components(comps...))
{{- end }}
{{- if or .Server.Http .Server.Grpc }}
	capOpts = append(capOpts, appkit.Servers(
	{{- if .Server.Grpc }}
		grpcserver.NewGRPCServerWithRegister(bootstrap.GetServer().GetGrpc(),
			append(newGRPCServerOptions(), b.GRPCChain()...), registerGRPCService, ready),
	{{- end }}
	{{- if .Server.Http }}
		httpserver.NewHTTPServer(bootstrap.GetServer().GetHttp(), router, ready),
	{{- end }}
	))
{{- end }}

	app := appkit.New(capOpts...)
	if err := app.Run(context.Background()); err != nil {
		baldlog.GetLogger().Error(context.Background(), "{{ .Meta.Name }} exited", "error", err)
		return err
	}
	return nil
}


// ready 探针：业务就绪检查（P0 优雅停机前须就绪）。
func ready(ctx context.Context) error { return nil }

// buildComponent 按 kind 构造托管组件（P12 第二步：kind 决定工厂）。
func buildComponent(kind, name, prefix string) (appkit.Component, error) {
	switch kind {
	// TODO: 为各 kind 接入真实组件工厂（db/redis/otlp/casbin/...）。
	case "heartbeat":
		return appkit.ComponentFunc(name, func(ctx context.Context) error {
			baldlog.GetLogger().Info(ctx, "heartbeat component started", "name", name)
			_ = prefix // 组件配置键前缀（config 读取 TODO）
			return nil
		}), nil
	default:
		return nil, fmt.Errorf("unknown component kind %q", kind)
	}
}
{{- if .Server.Grpc }}

// registerGRPCService 注册 gRPC service（业务 TODO）。
func registerGRPCService(s *grpc.Server) {}

// newGRPCServerOptions 构造 gRPC server 拦截器链（业务可扩展）。
func newGRPCServerOptions() []grpc.ServerOption {
	return []grpc.ServerOption{grpc.Creds(insecure.NewCredentials())}
}
{{- end }}

// ---- R1-2 审计后端热切换（逐后端 Mount/Unmount，K8s controller 语义） ----

// reconcileAudit 是期望态协调函数：配置键 audit.backends 声明「期望的审计后端
// 集合」，与实际态（rctx.Mounted()）做 diff，逐后端 Mount/Unmount——只更新变动
// 部分，失败不回滚、下次协调补齐。触发时机由框架负责：启动收敛期与配置热变更。
func reconcileAudit(ctx context.Context, rctx *appkit.ReconcileCtx) error {
	want := rctx.StringSlice("audit.backends")
	if len(want) == 0 {
		want = defaultAuditBackends // config 未设置时回退 AppSpec 声明
	}
	add, remove := appkit.DiffStrings(want, rctx.Mounted())
	if len(add) == 0 && len(remove) == 0 {
		return nil // 幂等：期望==实际，不抖动
	}

	baldlog.GetLogger().Info(ctx, "reconcile audit.backends",
		"add", strings.Join(add, ","), "remove", strings.Join(remove, ","))

	for _, name := range add {
		if err := rctx.Mount(ctx, name, &auditBackendComponent{name: name}); err != nil {
			baldlog.GetLogger().Error(ctx, "reconcile mount audit backend failed",
				"backend", name, "error", err) // 失败不回滚，下次协调补齐
		}
	}
	for _, name := range remove {
		if err := rctx.Unmount(ctx, name); err != nil {
			baldlog.GetLogger().Error(ctx, "reconcile unmount audit backend failed",
				"backend", name, "error", err)
		}
	}
	return nil
}

// auditors 记录当前生效的后端审计器（实际态）；Mount/Unmount 维护，名 == 后端名，
// 与 rctx.Mounted() 一一对应。锁仅保护 map；全局 Auditor 的重设由 applyAuditors 串行完成。
var auditors = struct {
	mu  sync.Mutex
	set map[string]audit.Auditor
}{set: make(map[string]audit.Auditor)}

// auditBackendComponent 是一个后端审计器组件：Mount 即注册进全局审计器，
// Unmount 即注销。
type auditBackendComponent struct{ name string }

func (c *auditBackendComponent) Name() string { return c.name }

func (c *auditBackendComponent) Start(ctx context.Context) error {
	a := buildAuditBackend(c.name)
	if a == nil {
		// 依赖未就绪：返回错误使挂载失败（不入实际态归属表），下次协调重试补齐。
		return fmt.Errorf("audit backend %q unavailable", c.name)
	}
	auditors.mu.Lock()
	auditors.set[c.name] = a
	auditors.mu.Unlock()
	applyAuditors()
	baldlog.GetLogger().Info(ctx, "audit backend mounted", "backend", c.name)
	return nil
}

func (c *auditBackendComponent) Dispose(ctx context.Context) error {
	auditors.mu.Lock()
	delete(auditors.set, c.name)
	auditors.mu.Unlock()
	applyAuditors()
	baldlog.GetLogger().Info(ctx, "audit backend unmounted", "backend", c.name)
	return nil
}

// buildAuditBackend 构造某后端的审计器（log 开箱即用；store/stream 依赖业务
// 的 DB/Redis 桥接，留 TODO）。返回 nil 表示依赖未就绪（挂载失败，下次重试）。
func buildAuditBackend(name string) audit.Auditor {
	switch name {
	case "log":
		return logAuditor{}
	// TODO: 接入 store/stream 后端（参考 examples/go-bald-admin 的
	// buildAuditBackend：依赖 bootstrappkg.DB / RedisCache.Client()）。
	}
	return nil
}

// applyAuditors 按后端名排序重建全局审计器（顺序确定，便于测试与排查日志）；
// 空则退化为 Nop，绝不阻断审计旁路。
func applyAuditors() {
	auditors.mu.Lock()
	names := make([]string, 0, len(auditors.set))
	for n := range auditors.set {
		names = append(names, n)
	}
	sort.Strings(names)
	list := make([]audit.Auditor, 0, len(names))
	for _, n := range names {
		list = append(list, auditors.set[n])
	}
	auditors.mu.Unlock()

	if len(list) == 0 {
		audit.SetAuditor(audit.NopAuditor())
		return
	}
	audit.SetAuditor(multiAuditor(list))
}

// logAuditor 是最小审计后端：事件落应用日志。
type logAuditor struct{}

func (logAuditor) Record(ctx context.Context, ev audit.AuditEvent) {
	baldlog.GetLogger().Info(ctx, "audit event",
		"object", ev.Object, "action", ev.Action, "result", string(ev.Result))
}

// multiAuditor 顺序广播到全部后端（核心包未提供，骨架内联最小实现）。
type multiAuditor []audit.Auditor

func (m multiAuditor) Record(ctx context.Context, ev audit.AuditEvent) {
	for _, a := range m {
		a.Record(ctx, ev)
	}
}

func main() {
	root := &cobra.Command{
		Use:   "{{ .Meta.Name }}",
		Short: "{{ .Meta.Desc }}",
		RunE:  serveRunE,
	}
	root.FParseErrWhitelist.UnknownFlags = true
	if err := root.Execute(); err != nil {
		osExit(1)
	}
}

var osExit = func(code int) { os.Exit(code) }
`

// appspecData 是模板渲染用的内部视图（proto 生成的 message 字段均为指针，
// 此处保留指针以匹配生成的 API；模板通过 Go 模板自动解引用访问字段）。
type appspecData struct {
	Meta             *appspecv1.AppMeta
	Server           *appspecv1.ServerSpec
	Capability       *appspecv1.CapabilitySpec
	Components       []*appspecv1.ComponentSpec
	AuditBackends    []string
	BundleNormalized bool
}

func renderAppSpec(data appspecData, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	t := template.Must(template.New("appspec").Parse(appspecTmpl))
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// 格式化失败也落盘（便于排查模板语法），但回显原始错误。
		_ = os.WriteFile(path, buf.Bytes(), 0o644)
		return fmt.Errorf("gofmt generated main.go: %w", err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return err
	}
	fmt.Println("generated app (spec-driven):", path)
	return nil
}
