// Package flatbuffers provides a [encoding.Codec] implementation using
// Google FlatBuffers.
//
// FlatBuffers is a zero-copy serialization format. Unlike other codecs
// (JSON, Protobuf, etc.), FlatBuffers does not have a generic Marshal/Unmarshal
// API — serialization requires a generated Builder and deserialization requires
// a generated type that implements flatbuffers.FlatBuffer.
//
// To bridge this with the encoding.Codec interface, this package expects:
//   - Marshal:   the value must implement [FlatBufferMarshaler].
//   - Unmarshal: the target must implement [flatbuffers.FlatBuffer].
//
// Registration is explicit: encoding.MustRegister(flatbuffers.New()).
package flatbuffers

import (
	"fmt"

	fb "github.com/google/flatbuffers/go"

	"github.com/kalandramo/bald/encoding"
)

// Name is the name registered for the FlatBuffers codec.
const Name = "flatbuffers"

// New returns a fresh flatbuffers codec for explicit registration
// via encoding.MustRegister.
func New() encoding.Codec { return codec{} }

// Compile-time guarantee that codec satisfies the encoding.Codec contract.
var _ encoding.Codec = codec{}

// FlatBufferMarshaler is implemented by generated FlatBuffer types to produce
// a serialized buffer. Typically, the flatc compiler generates a
// Pack() or similar method that writes into a flatbuffers.Builder.
type FlatBufferMarshaler interface {
	// Pack builds the FlatBuffer and returns the finished bytes.
	PackFlatBuffer() ([]byte, error)
}

// codec implements encoding.Codec using Google FlatBuffers.
type codec struct{}

// Marshal encodes v into FlatBuffer bytes.
// v must implement [FlatBufferMarshaler].
func (codec) Marshal(v any) ([]byte, error) {
	m, ok := v.(FlatBufferMarshaler)
	if !ok {
		return nil, fmt.Errorf("flatbuffers: value %T does not implement FlatBufferMarshaler", v)
	}
	return m.PackFlatBuffer()
}

// Unmarshal decodes FlatBuffer data into v.
// v must be a pointer to a type that implements [flatbuffers.FlatBuffer]
// (i.e. has an Init method generated by flatc).
//
// FlatBuffers is zero-copy: fb.GetRootAs performs no bounds checking, so a
// truncated or corrupt buffer would otherwise panic deep inside field access
// (or silently yield garbage). Unmarshal therefore validates the buffer header
// — it must be long enough to hold the root offset and the resulting root
// position must lie within the buffer — before handing it to the library.
func (codec) Unmarshal(data []byte, v any) error {
	t, ok := v.(fb.FlatBuffer)
	if !ok {
		return fmt.Errorf("flatbuffers: target %T does not implement flatbuffers.FlatBuffer", v)
	}

	if err := validateRootBuffer(data); err != nil {
		return err
	}

	fb.GetRootAs(data, 0, t)
	return nil
}

// validateRootBuffer checks that data is long enough to contain the 4-byte
// root offset and that the root position it points to lies within data.
// It mirrors what fb.GetRootAs assumes but does not verify.
func validateRootBuffer(data []byte) error {
	// The root offset is a UOffsetT (4 bytes) read from data[0:].
	if len(data) < fb.SizeUOffsetT {
		return fmt.Errorf("flatbuffers: buffer too short (%d bytes, need at least %d for the root offset)",
			len(data), fb.SizeUOffsetT)
	}

	rootOffset := fb.GetUOffsetT(data)
	// Following fb.GetRootAs, the root position is rootOffset + 0.
	// Require it to be a valid index (and leave room for the vtable offset).
	if int(rootOffset) > len(data)-fb.SizeSOffsetT {
		return fmt.Errorf("flatbuffers: root offset %d out of range for %d-byte buffer",
			rootOffset, len(data))
	}

	return nil
}

// Name returns the codec name.
func (codec) Name() string {
	return Name
}
