// Package thrift provides a [encoding.Codec] implementation using
// Apache Thrift's binary protocol.
//
// Thrift is a binary serialization format originally developed at Facebook
// and now maintained by the Apache Software Foundation. It is widely used
// in high-performance RPC frameworks (e.g. CloudWeGo Kitex, Apache Thrift).
//
// Registration is explicit: encoding.MustRegister(thrift.New()).
//
// Note: Thrift serialization requires the value to implement
// thrift.TStruct (i.e. have Read/Write methods generated by the Thrift
// compiler). Plain Go structs without generated code will return an error.
package thrift

import (
	"context"
	"fmt"

	"github.com/apache/thrift/lib/go/thrift"

	"github.com/kalandramo/bald/encoding"
)

// Name is the name registered for the Thrift codec.
const Name = "thrift"

// New returns a fresh thrift codec for explicit registration
// via encoding.MustRegister.
func New() encoding.Codec { return codec{} }

// Compile-time guarantee that codec satisfies the encoding.Codec contract.
var _ encoding.Codec = codec{}

// codec implements encoding.Codec using Apache Thrift binary protocol.
//
// It is stateless: TSerializer/TDeserializer are created per call. Thrift does
// not document them as safe for concurrent use, so sharing one instance across
// calls would be a latent data race once a codec value is held by a transport.
type codec struct{}

// Marshal encodes v into Thrift binary bytes.
// v must implement thrift.TStruct (i.e. be a generated Thrift struct).
func (codec) Marshal(v any) ([]byte, error) {
	t, ok := v.(thrift.TStruct)
	if !ok {
		return nil, fmt.Errorf("thrift: value %T does not implement thrift.TStruct", v)
	}
	return thrift.NewTSerializer().Write(context.Background(), t)
}

// Unmarshal decodes Thrift binary data into v.
// v must be a pointer to a type that implements thrift.TStruct.
func (codec) Unmarshal(data []byte, v any) error {
	t, ok := v.(thrift.TStruct)
	if !ok {
		return fmt.Errorf("thrift: target %T does not implement thrift.TStruct", v)
	}
	return thrift.NewTDeserializer().Read(context.Background(), t, data)
}

// Name returns the codec name.
func (codec) Name() string {
	return Name
}
