package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"

	appspecv1 "github.com/kalandramo/bald/pkg/conf/gen/go/bald/appspec/v1"
)

// appspecTmpl 是 P12 第二步「方言驱动生成」的 main.go 模板：消费 AppSpec，
// 据此装配 appkit 全原语（Capability/S1、Component/C1、Reconcile/R1-2、
// Mount/A1、bundle/P10）。生成的是可编译骨架——业务 handler/grpc 注册位留 TODO，
// 但框架装配（server/component/capability/reconcile）已按 AppSpec 真实接线。
//
// 设计对齐 go-wind-admin 的 proto 分层：把「应用装配」本身升格为单一 proto 真相源，
// 取代 gen app 第一版的硬编码模板（模板 + 手填配置键 = 双真相源）。
var appspecTmpl = `// Code generated by "bald gen app --spec". DO NOT EDIT.
//
// 本文件由 AppSpec 方言驱动生成（P12 第二步）。AppSpec 是应用装配的单一真相源，
// 任何装配变更应先改 AppSpec 再重新生成，而非手改此文件。
package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
{{- if .Server.Http }}
	"net/http"
{{- end }}

	"github.com/kalandramo/bald/pkg/appkit"
	baldconf "github.com/kalandramo/bald/pkg/conf"
	baldlog "github.com/kalandramo/bald/pkg/log"
	"github.com/kalandramo/bald/pkg/middleware/bundle"
	"github.com/kalandramo/bald/pkg/server"
)

func serveRunE(_ *cobra.Command, _ []string) error {
	bootstrap := baldconf.NewBootstrap()
	// 全局日志后端（slog 门面），可经 config 的 logger.* 重载。
	baldlog.SetLogger(baldlog.NewSlogLogger(baldlog.NewOptions()))

	// S1 能力声明（启动期 fail-fast）：Provides/Requires 任一项缺失即 Run 失败。
	capOpts := []appkit.Option{
		appkit.Name("{{ .Meta.Name }}"),
		appkit.Version("v0.1.0"),
		appkit.ConfigFile("configs/{{ .Meta.Name }}.yaml"),
		appkit.WatchConfigFile(true),
		// R1-2 期望态协调：以 audit.backends 为期望态，运行期热切审计后端。
		appkit.Reconcile("audit.backends", reconcileAudit),
	}
	{{- if .Capability }}
	{{- range .Capability.Provides }}
	capOpts = append(capOpts, appkit.Provides("{{ . }}"))
	{{- end }}
	{{- range .Capability.Requires }}
	capOpts = append(capOpts, appkit.Requires("{{ . }}"))
	{{- end }}
	{{- end }}

	// bundle：切片关注点链序固化（P10）。
	b := bundle.New(
		{{- if .BundleNormalized }}
		bundle.Normalized(), // P9 归一化
		{{- end }}
	)
	_ = b

	app := appkit.New(capOpts...)

	// 组件挂载：由 ComponentSpec 驱动，kind 决定工厂（C1 生命周期 + A1 热插拔）。
	{{- range .Components }}
	if comp, err := buildComponent("{{ .Kind }}", "{{ .Name }}", "{{ .ConfigPrefix }}"); err != nil {
		return err
	} else if err := app.MountComponent(context.Background(), comp); err != nil {
		return err
	}
	{{- end }}

	// 服务装配：由 ServerSpec 驱动。
	var servers []server.Server
	{{- if .Server.Http }}
	servers = append(servers, server.NewHTTPServer(bootstrap.GetHttp(), http.NewServeMux(), ready))
	{{- end }}
	{{- if .Server.Grpc }}
	servers = append(servers, server.NewGRPCServerWithRegister(
		bootstrap.GetGrpc(), newGRPCServerOptions(), registerGRPCService, ready))
	{{- end }}
	{{- if .Server.Gateway }}
	// TODO: 注册 grpc-gateway 路由（业务）。需引入
	// github.com/grpc-ecosystem/grpc-gateway/v2/runtime 并反向代理 gRPC。
	{{- end }}
	if len(servers) > 0 {
		capOpts = append(capOpts, appkit.Servers(servers...))
	}

	if err := app.Run(context.Background()); err != nil {
		baldlog.GetLogger().Error(context.Background(), "{{ .Meta.Name }} exited", "error", err)
		return err
	}
	return nil
}

// ready 探针：业务就绪检查（P0 优雅停机前须就绪）。
func ready(ctx context.Context) error { return nil }

// buildComponent 按 kind 构造托管组件（P12 第二步：kind 决定工厂）。
func buildComponent(kind, name, prefix string) (appkit.Component, error) {
	switch kind {
	// TODO: 为各 kind 接入真实组件工厂（heartbeat/db/redis/otlp/casbin/...）。
	case "heartbeat":
		return appkit.ComponentFunc(name, func(ctx context.Context) error {
			baldlog.GetLogger().Info(ctx, "heartbeat component started", "name", name)
			return nil
		}), nil
	default:
		return nil, fmt.Errorf("unknown component kind %q", kind)
	}
}

// registerGRPCService 注册 gRPC service（业务 TODO）。
func registerGRPCService(s *grpc.Server) {}

// newGRPCServerOptions 构造 gRPC server 拦截器链（业务可扩展）。
func newGRPCServerOptions() []grpc.ServerOption {
	return []grpc.ServerOption{grpc.Creds(insecure.NewCredentials())}
}

func reconcileAudit(ctx context.Context, r *appkit.ReconcileCtx) error {
	want := parseAuditBackends(r.Viper.GetString("audit.backends"))
	have := r.Mounted()
	add, remove := appkit.DiffStrings(want, have)
	if len(add) == 0 && len(remove) == 0 {
		return nil
	}
	// TODO: 逐后端 Mount/Unmount（参考 examples/go-bald-admin 的 auditBackendComponent）。
	_ = add
	_ = remove
	return nil
}

func parseAuditBackends(s string) []string {
	var out []string
	for _, raw := range strings.FieldsFunc(s, func(r rune) bool { return r == ',' || r == ' ' }) {
		if b := strings.TrimSpace(raw); b != "" {
			out = append(out, b)
		}
	}
	return out
}

func main() {
	root := &cobra.Command{
		Use:   "{{ .Meta.Name }}",
		Short: "{{ .Meta.Desc }}",
		RunE:  serveRunE,
	}
	root.FParseErrWhitelist.UnknownFlags = true
	if err := root.Execute(); err != nil {
		osExit(1)
	}
}

var osExit = func(code int) { os.Exit(code) }
`

// appspecData 是模板渲染用的内部视图（proto 生成的 message 字段均为指针，
// 此处保留指针以匹配生成的 API；模板通过 Go 模板自动解引用访问字段）。
type appspecData struct {
	Meta             *appspecv1.AppMeta
	Server           *appspecv1.ServerSpec
	Capability       *appspecv1.CapabilitySpec
	Components       []*appspecv1.ComponentSpec
	AuditBackends    []string
	BundleNormalized bool
}

func renderAppSpec(data appspecData, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	t := template.Must(template.New("appspec").Parse(appspecTmpl))
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// 格式化失败也落盘（便于排查模板语法），但回显原始错误。
		_ = os.WriteFile(path, buf.Bytes(), 0o644)
		return fmt.Errorf("gofmt generated main.go: %w", err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return err
	}
	fmt.Println("generated app (spec-driven):", path)
	return nil
}
